<?php
/*
 * CLASS DESCRIPTION:
 * 
 */
final class blankClassTemplate{
/* CLASS PROPERTIES */
//PRIVATE SCOPE

//PROTECTED SCOPE

//PUBLIC SCOPE

/* CLASS OBJECTS */
//PRIVATE SCOPE

//PROTECTED SCOPE

//PUBLIC SCOPE

/* CLASS METHODS */
//PRIVATE SCOPE

//PROTECTED SCOPE

//PUBLIC SCOPE

/* CLASS CONSTRUCT METHOD */
public function __construct(){/* START CONSTRUCT METHOD DEFINITION */
	
}/* [END CONSTRUCT METHOD DEFINITION] */}?>